apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: TARGET_K8S_NAMESPACE
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: MWYyZDFlMmU2N2Rm