apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: TARGET_K8S_NAMESPACE
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      priorityClassName: napptive-high-priority
      containers:
        - name: postgres
          image: bitnami/postgresql:12.1.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRESQL_REPLICATION_MODE
              value: master
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgredb
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
