apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: TARGET_K8S_NAMESPACE
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
  selector:
    app: postgres
