apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-slave
  namespace: TARGET_K8S_NAMESPACE
  labels:
    app: postgres-slave
spec:
  serviceName: "postgres-slave"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-slave
  template:
    metadata:
      labels:
        app: postgres-slave
    spec:
      priorityClassName: napptive-high-priority
      containers:
        - name: postgres-slave
          image: bitnami/postgresql:12.1.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_REPLICATION_MODE
              value: slave
            - name: POSTGRESQL_REPLICATION_MODE
              value: slave
            - name: POSTGRESQL_USERNAME
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: password
            - name: POSTGRESQL_DATABASE
              value: postgresdb
            - name: POSTGRESQL_REPLICATION_USER
              value: postgres
            - name: POSTGRESQL_REPLICATION_PASSWORD
              value: password
            - name: POSTGRESQL_MASTER_HOST
              value: postgres
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgredb
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
