kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: TARGET_K8S_NAMESPACE
  labels:
    app: postgres
spec:
  storageClassName: postgres-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi