name: Publish latest component version

on:
    push:
      branches: [ main ]
  
jobs:  
    build:
      name: Push docker images
      runs-on: ubuntu-22.04
        
      steps: 
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
     
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      - name: Build and push Docker images
        run: make docker-push
        env:
          VERSION: latest
          TARGET_DOCKER_REGISTRY: napptive
               


      
    
